on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: build project
        run: |
          ./scripts/buildprod.sh

      - name: "I'm absolutely not not running google cloud, no chance"
        run: gcloud builds submit || true
